import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer className="fixed bottom-0 left-0 right-0 flex md:flex-row flex-col items-center justify-between px-4 py-6 bg-gray-100">
          <div className='text-black md:text-xl flex items-center justify-center w-full'>
            <p>Footer</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
